"""Auto migration

Revision ID: 64647797c939
Revises: 223a1f6f21cc
Create Date: 2026-02-04 09:40:24.636114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64647797c939'
down_revision = '223a1f6f21cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_c2b_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('trans_id', sa.String(length=100), nullable=False),
    sa.Column('trans_time', sa.String(length=20), nullable=False),
    sa.Column('trans_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('business_short_code', sa.String(length=10), nullable=False),
    sa.Column('bill_ref_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('org_account_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('third_party_trans_id', sa.String(length=100), nullable=True),
    sa.Column('msisdn', sa.String(length=15), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_c2b_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_c2b_bill_ref', ['bill_ref_number'], unique=False)
        batch_op.create_index('idx_c2b_msisdn_time', ['msisdn', 'trans_time'], unique=False)
        batch_op.create_index('idx_c2b_processed', ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_c2b_transactions_msisdn'), ['msisdn'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_c2b_transactions_trans_id'), ['trans_id'], unique=True)

    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_type', sa.Enum('C2B', 'B2C', 'STK_PUSH', name='mpesatransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('account_reference', sa.String(length=50), nullable=True),
    sa.Column('transaction_desc', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='mpesatransactionstatus'), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_code', sa.String(length=10), nullable=True),
    sa.Column('result_desc', sa.Text(), nullable=True),
    sa.Column('mpesa_data', sa.JSON(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_mpesa_account_ref', ['account_reference'], unique=False)
        batch_op.create_index('idx_mpesa_initiated_at', ['initiated_at'], unique=False)
        batch_op.create_index('idx_mpesa_phone_status', ['phone_number', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'), ['checkout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_merchant_request_id'), ['merchant_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_mpesa_receipt_number'), ['mpesa_receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_phone_number'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_mpesa_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_merchant_request_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'))
        batch_op.drop_index('idx_mpesa_phone_status')
        batch_op.drop_index('idx_mpesa_initiated_at')
        batch_op.drop_index('idx_mpesa_account_ref')

    op.drop_table('mpesa_transactions')
    with op.batch_alter_table('mpesa_c2b_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_c2b_transactions_trans_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_c2b_transactions_msisdn'))
        batch_op.drop_index('idx_c2b_processed')
        batch_op.drop_index('idx_c2b_msisdn_time')
        batch_op.drop_index('idx_c2b_bill_ref')

    op.drop_table('mpesa_c2b_transactions')
    # ### end Alembic commands ###
